function CSSPost(d,e,a){var b=window.document.createElement("link");var c=e||window.document.getElementsByTagName("script")[0];b.href=d;b.rel="stylesheet";c.parentNode.insertBefore(b,c);setTimeout(function(){b.media=a||"all"})}
CSSPost("https://cdn.sophiainstitute.id/website/code/CSS-CarouselPost.min.css");

function PostM(f,e,i){'use strict';var h=window.document.createElement("script"),g=e||window.document.getElementsByTagName("script")[0];h.async=!0,h.src=f,g.parentNode.insertBefore(h,g),setTimeout(function(){h.media=i||"all"})}
PostM('https://cdn.sophiainstitute.id/website/code/Permalinks-bar.min.js');
PostM('https://code.responsivevoice.org/responsivevoice.js?key=BACrqbq3');

/*! Ebook Slide */
var jumlah=6;var containernyaId="ignielRandom";function getRandomInt(d,c){return Math.floor(Math.random()*(c-d+1))+d}function shuffleArray(f){var h,g,e=f.length;if(0===e){return falplse}for(;--e;){h=Math.floor(Math.random()*(e+1)),g=f[e],f[e]=f[h],f[h]=g}return f}function randomPost(d){var c=getRandomInt(1,d.feed.openSearch$totalResults.$t-jumlah);document.write('<script src="https://ebook.sophiainstitute.id/feeds/posts/summary?alt=json-in-script&start-index=1&max-results=11&callback=ignielRandom"><\/script>')}function ignielRandom(q){var p="https://4.bp.blogspot.com/-Mpgs0kSln2I/WnRcTqvlOII/AAAAAAAAFh4/VTrxpLBIC7oxQi6xs2t6z0W2sV2h_zSiwCLcBGAs/w300-h225-p-k-no-nu/ignielcom-no-image.png";for(var k,e,n,h,m,f=document.getElementById(containernyaId),o=shuffleArray(q.feed.entry),c="<div class='team-slider owl-carousel'>",d=0,g=o.length;d<g;d++){for(var l=0,j=o[d].link.length;l<j;l++){k="alternate"==o[d].link[l].rel?o[d].link[l].href:"#",n=o[d].category[0].term,h=o[d].summary.$t.substring(0,90),m=o[d].title.$t.substring(0,25),"media$thumbnail" in o[d]?e=o[d].media$thumbnail.url.replace(/\=s[0-9]+(\-c)?/,"=s360-c").replace(/\/s[0-9]+(\-c)?/,"/s360-c"):(e=p,p="https://4.bp.blogspot.com/-Mpgs0kSln2I/WnRcTqvlOII/AAAAAAAAFh4/VTrxpLBIC7oxQi6xs2t6z0W2sV2h_zSiwCLcBGAs/w300-h225-p-k-no-nu/ignielcom-no-image.png")}c+='<div class="single-box text-center"><div class="img-area"><a href="'+k+'" title="'+m+'"><img class="img-fluid move-animation" src="'+e+'" alt="'+m+'" title="'+m+'"/></a></div><div class="info-area"><a class="linktit" href="'+k+'" title="'+m+'"><h4>'+m+"...</h4><h5>EBOOK</h5></a><p>"+h+'...</p><a href="'+k+'" title="'+m+'">Download</a></div></div>'}f.innerHTML=c+"</div>"}document.write('<script src="'+window.location.origin+'/feeds/posts/summary?alt=json-in-script&max-results=0&callback=randomPost"><\/script><script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"><\/script>');
/*! Scriptnya */
